dist: trusty
sudo: false
language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.2
addons:
  postgresql: '9.6' # Use postgres 9.6
before_script:
# Create the test database
- psql -c 'create database peepchat_test;' -U postgres
